title: ReFab3D
description: Refabrication de pi√®ces introuvables par impression 3D
theme: minima

markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - ../parts
